### ISSUE TITLE
Добавить новые типы пуль (SplashBullet и SpreadBullet) + подумать над архитектурой

### ISSUE THREAD

**Issue by Gungniir** [Tower-Defence-Game/unity#13]
## Введение
Для реализации наших новых башен, необходимо добавить новые виды пуль:

- SplashBullet  - Достигая нужной точки (или врага...) должна наносить урон всем Enemy в определённом радиусе
- SpreadBullet - Достигая нужного врага, должна нанести урон не только ему, но и окружающих врагов с определённым элементом (и так далее), но не должно создаваться циклов

Возможно, стоит подумать над тем, чтобы заменить IBullet на AbstarctBullet, но я пока не вижу причин для этого... Хотя, возможно, это будет удобно и единообразно

## Что делать
Очевидно! Новые пульки:

- [x] SplashBullet  
- [x] SpreadBullet

**Comment by Kugeki** [comment]
Готово. #23 #24
